djangojokes/urls.py
import private_storage.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),

    # User Management
    path('account/', include('users.urls')),
    path("account/", include("allauth.urls")),

    # Private media & files
    path('media/private/', include(private_storage.urls)),

    # Local Apps
    path("jobs/", include("jobs.urls")),
    path("jokes/", include("jokes.urls")),
    path("", include("pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
## The static() fcn, above, is a helper fcn that only works when settings.DEBUG is set to True. 
## So, you don’t have to worry about removing this code when deploying to production. 
## It'll be ignored.
## We are NOT deploying storage to AWS S3 buckets rt now, cuz NO WORKY the way class said it does.
## IN future, go thru free AWS S3 training on their site and see if you can figure it out.


if (settings.DEBUG):
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


## I want to keep these notes.
"""
URL configuration for djangojokes project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

jobs/urls.py
from django.urls import path
from .views import JobApplicationView, JobApplicationThanksView


app_name = "jobs"


urlpatterns = [
    path("job-app/", JobApplicationView.as_view(), name="app"),
    path("job-app/thanks/", JobApplicationThanksView.as_view(), name="thanks")
]

jokes/urls.py
from django.urls import path
from .views import (JokeCreateView, JokeDeleteView, JokeDetailView, JokeListView, 
                    JokeUpdateView, vote)
## Parens above are just to show how to split imports across multiple lines


app_name = "jokes"


urlpatterns = [
    ## Remember only URL paths beginning with '/jokes/' will be handed off to the URLConf 
    ## of the jokes app, so "" will actually be "/jokes/".
    path("", JokeListView.as_view(), name="list"),
    path("joke/create/", JokeCreateView.as_view(), name="create"),
    ## The default template_name for a DeleteView: `<app_name>/<model-name>_confirm_delete.html`
    path("joke/<slug>/delete/", JokeDeleteView.as_view(), name="delete"),
    path("joke/<slug>/update/", JokeUpdateView.as_view(), name="update"),
    path("joke/<slug>/", JokeDetailView.as_view(), name="detail"),
    ## When a URL matching this pattern, below, is requested, 
    # the vote() View fcn will be called and passed the slug from the URL.
    path('joke/<slug>/vote/', vote, name='ajax-vote'),
    ## Filtering Results by Category, Tag, or Creator:
    path("category/<slug>/", JokeListView.as_view(), name="category"),
    path("tag/<slug>/", JokeListView.as_view(), name="tag"),
    path("creator/<slug>/", JokeListView.as_view(), name="creator"),
    ## MyJokes adjustment from Copilot:
    ## New route for "my_jokes" to filter just that user's created jokes.
    path('my-jokes/', JokeListView.as_view(), name='my_jokes'),
]

pages/urls.py
from django.urls import path
from pages.views import HomePageView, AboutPageView


app_name = "pages"


urlpatterns = [
    path("", HomePageView.as_view(), name="homepage"),
    path("about/", AboutPageView.as_view(), name="about")
]

templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  {% load static %}

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" 
    rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" 
    crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/main.css '%}"/>
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" />
  
  <!-- ADD FONT AWESOME FROM https://fontawesome.com/ -->
  <script src="https://kit.fontawesome.com/5edc2e2a09.js" crossorigin="anonymous">
  </script>

  {% block javascript %}{% endblock %}
  
  <title>{% block title %}{% endblock %} | Django Jokes</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'pages:homepage' %}">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="img-fluid"/>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-expanded="false" aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a id="home-nav-link" class="nav-link" href="{% url 'pages:homepage' %}">
              Home
            </a> 
          </li>
          <li class="nav-item">
            <a id="jokes-nav-link" class="nav-link" href="{% url 'jokes:list' %}">
              Jokes
            </a>
          </li>
          <li class="nav-item">
            <a id="about-nav-link" class="nav-link" href="{% url 'pages:about' %}">
              About
            </a>
          </li>
          {% if not user.is_authenticated %}
            <li class="nav-item">
              <a id="login-nav-link" class="nav-link" href="{% url 'account_login' %}">
                Log in
              </a>
            </li>
            <li class="nav-item">
              <a id="register-nav-link" class="nav-link" href="{% url 'account_signup' %}">
                Register
              </a>
            </li>
          {% else %}  
            <li class="nav-item dropdown">
              <a id="navbarDropdown" 
                class="nav-link dropdown-toggle" 
                href="#"  
                role="button" 
                data-bs-toggle="dropdown"
                aria-haspopup="true" 
                aria-expanded="false">
                Me
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a id="my-account-nav-link" 
                  class="dropdown-item"  
                  href="{% url 'my-account' %}">My Account</a>
                <a id="my-jokes-nav-link" 
                  class="dropdown-item" 
                  href="{% url 'jokes:my_jokes' %}?order={{ order }}&direction={{ direction }}">
                  My Jokes</a>
                <div class="dropdown-divider"></div>
                <form method="post" action="{% url 'account_logout' %}">
                  {% csrf_token %}
                  <button id="logout-nav-btn" 
                    class="btn dropdown-item" 
                    name="LOG OUT" 
                    alt="Log out of your account" 
                    type="submit">Log Out</button>
                </form>
              </div>
            </li>
          {% endif %} 
        </ul>

        <form id="search-form" class="row my-2 my-lg-0 row" action="{% url 'jokes:list' %}">
          <input id="search-input" 
            class="form-control me-sm-2 col" 
            type="search" 
            placeholder="Search term" 
            aria-label="Search"
            value="{{ request.GET.search_qry }}"
            alt="Enter a search term to search jokes"
            name="search_qry" />
          <button id="search-btn" 
            class="btn btn-outline-success my-2 my-sm-0 me-4 col" 
            type="submit" 
            alt="Search button: Click or tap to search jokes" 
            name="Search">Search</button>
        </form>
      </div>
    </nav>
  </header>

  <main class="m-4 pb-5">
    <!-- EXAMPLE of using Msgs in HTML.  You still need the get meth in the View. -->
    {% if messages %}
      <ul>
        {% for message in messages %}
        <div class="alert message{{ message.tags }} alert-dismissable" role="alert">
          <b>{{ message }}</b>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      </ul>
    {% endif %}
    
    {% block main %}
      <h2>Welcome!</h2>
    {% endblock %}
  </main>

  <footer class="fixed-bottom bg-light row">
    <div class="col">
      <div class="float-end m-1 me-2">Copyright &copy; 2022 Django Jokes.</div>
      <nav>
        <ul class="nav">
          <li class="nav-item">
            <a id="about-footer-link" class="nav-link" href="{% url 'pages:about' %}">
              About
            </a>
          </li>
          {% if user.is_authenticated and user.is_staff %}
            <li class="nav-item">
              <a id="admin-footer-link" class="nav-link" href="{% url 'admin:index' %}">
                Admin
              </a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a id="careers-footer-link" class="nav-link" href="{% url 'jobs:app' %}">
              Careers
            </a>
          </li>
          <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
        </ul>
      </nav>
    </div>
    </nav>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>
</body>
</html>