djangojokes/urls.py
import private_storage.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),

    # User Management
    path('account/', include('users.urls')),
    path("account/", include("allauth.urls")),

    # Private media & files
    path('media/private/', include(private_storage.urls)),

    # Local Apps
    path("jobs/", include("jobs.urls")),
    path("jokes/", include("jokes.urls")),
    path("", include("pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
## The static() fcn, above, is a helper fcn that only works when settings.DEBUG is set to True. 
## So, you don’t have to worry about removing this code when deploying to production. 
## It'll be ignored.
## We are NOT deploying storage to AWS S3 buckets rt now, cuz NO WORKY the way class said it does.
## IN future, go thru free AWS S3 training on their site and see if you can figure it out.


if (settings.DEBUG):
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


## I want to keep these notes.
"""
URL configuration for djangojokes project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

jobs/urls.py
from django.urls import path
from .views import JobApplicationView, JobApplicationThanksView


app_name = "jobs"


urlpatterns = [
    path("job-app/", JobApplicationView.as_view(), name="app"),
    path("job-app/thanks/", JobApplicationThanksView.as_view(), name="thanks")
]

jokes/urls.py
from django.urls import path
from .views import (JokeCreateView, JokeDeleteView, JokeDetailView, JokeListView, 
                    JokeUpdateView, vote)
## Parens above are just to show how to split imports across multiple lines


app_name = "jokes"


urlpatterns = [
    ## Remember only URL paths beginning with '/jokes/' will be handed off to the URLConf 
    ## of the jokes app, so "" will actually be "/jokes/".
    path("", JokeListView.as_view(), name="list"),
    path("joke/create/", JokeCreateView.as_view(), name="create"),
    ## The default template_name for a DeleteView: `<app_name>/<model-name>_confirm_delete.html`
    path("joke/<slug>/delete/", JokeDeleteView.as_view(), name="delete"),
    path("joke/<slug>/update/", JokeUpdateView.as_view(), name="update"),
    path("joke/<slug>/", JokeDetailView.as_view(), name="detail"),
    ## When a URL matching this pattern, below, is requested, 
    # the vote() View fcn will be called and passed the slug from the URL.
    path('joke/<slug>/vote/', vote, name='ajax-vote'),
    ## Filtering Results by Category, Tag, or Creator:
    path("category/<slug>/", JokeListView.as_view(), name="category"),
    path("tag/<slug>/", JokeListView.as_view(), name="tag"),
    path("creator/<slug>/", JokeListView.as_view(), name="creator"),
    ## MyJokes adjustment from Copilot:
    ## New route for "my_jokes" to filter just that user's created jokes.
    path('my-jokes/', JokeListView.as_view(), name='my_jokes'),
]

jokes/forms.py
from django.forms import ModelForm, Textarea
from .models import Joke


class JokeForm(ModelForm):
    class Meta:
        model = Joke
        fields = ["question", "answer", "category", "tags"]
        widgets = {
            "question": Textarea(attrs={'cols': 80, 'rows': 3, 'autofocus': True}),
            "answer": Textarea(attrs={'cols': 80, 'rows': 2, 'placeholder': 'Make it funny!', 
                                      'required': True}),
        }
        help_texts = {
            'question': 'No dirty jokes please.',
            'tags': 'Use Ctrl-click to select multiple tags.'
        }

jokes/views.py
import json
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q  ## Allows compound queries using conditions, like AND or OR, etc.
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from .models import Joke, JokeVote
from .forms import JokeForm

## These are class based Views
## ------------------------------
## BEGIN
class JokeCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Joke
    ## When using model form, means you can't use fields here.
    ## You wouldn't  want to anyway, b/c then you can't style these fields.
    # fields = ["question", "answer"]
    form_class = JokeForm ## Joke Model Form
    success_message = "Joke created successfully."


    ## @override
    def form_valid(self, form):
        """ Takes a form parameter, which has an instance property holding the data in the form object.  
        Here, adding another attribute, user, to that form object before saving."""
        form.instance.user = self.request.user
        ## After making the above change, call and return form_valid() on the superclass, 
        # which takes care of saving the form and redirecting to the success URL.
        return super().form_valid(form)
## END class


## BEGIN
class JokeDeleteView(UserPassesTestMixin, DeleteView):
    model = Joke
    ## reverse_lazy() works just like reverse(): 
    ## It returns the URL based on the passed-in URL pattern name. 
    # But unlike reverse(), it waits to get the URL until it is needed.
    success_url = reverse_lazy("jokes:list")
    ## We use reverse_lazy() here because the view is created before the URL configuration.
    ## So, if you try to use reverse(), you will likely get an error about a circular import. 
    ## The issue with using reverse() is the view needs the URLConf to have already been created, 
    # but the URLConf imports the view. So, it cannot be created until the view exists.


    """ UserPassesTestMixin requires a test_func() method, which returns True if the user passes the test
      and False otherwise."""
    ## @override
    def test_func(self):
        """ Returns True if and only if the logged-in user is the user who created the joke. """
        obj = self.get_object()
        return self.request.user == obj.user
    

    ## @override
    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        return result


    ## @override
    def form_valid(self, form):
        messages.success(self.request, 'Joke deleted.')
        return super().form_valid(form)
## END class


## BEGIN
class JokeDetailView(DetailView):
    ## Just like a ListView, a minimal DetailView only requires the model to query.
    model = Joke
    ## Default name of the template used by the JokeDetailView: 
    ## `<app_name>/<model>_detail.html`
    # e.g.: `jokes/joke_detail.html`
## END class


## BEGIN
class JokeListView(ListView):
    ## A minimal ListView is incredibly simple. 
    ## It just requires the model to query (ex. below):
    model = Joke
    ## Notice, above, you do not define a template_name attribute as you did with HomePageView. 
    ## When no template_name is defined for a ListView, Django infers a template_name as: 
    #### `<app_name>/<model>_list.html`
    ## ...Where <app_name> is the name of the app (i.e., jokes). 
    ## And, <model> is the lowercase name of the model. 
    ## So, for JokeListView, Django is looking for the template at: 
    #### `jokes/joke_list.html`
    #
    # Adding in pagination:  It's this ez w/ Django!
    ## When you add the paginate_by attribute to the ListView, 
    # you get access to a new page_obj in the context.
    paginate_by = 10
    ## The page_obj object includes the following properties:
        ## page_obj.has_previous – True if the current page is not the first page.
        ## page_obj.previous_page_number – The number of the previous page.
        ## page_obj.has_next – True if the current page is not the last page.
        ## page_obj.next_page_number –The number of the next page.
        ## page_obj.number – The current page number.
        ## page_obj.paginator.num_pages – The total number of pages.
    #
    ## You can control the ordering of ListViews using the ordering attribute.
    ## Prepend w/ a minus sign for descending order.  Ascending order is the default.
    ## Works great if you always want to sort in the same way, but not if you want dynamic sorting.
    # ordering = ['-question']


    def get_order_fields(self):
        """ Returns a dictionary mapping friendly names to field names and lookups.
        """
        return {
            'joke': 'question',
            'category': 'category__category',
            'creator': 'user__username',
            'created': 'created',
            'updated': 'updated',
            'default_key': 'updated' ## the default field to order by if order_key is either unspecified or invalid
        }
    

    def get_order_settings(self):
        order_fields = self.get_order_fields()
        default_order_key = order_fields['default_key']
        order_key = self.request.GET.get('order', default_order_key)
        direction = self.request.GET.get('direction', 'desc')
        # If order_key is invalid, use default
        if (order_key not in order_fields):
            order_key = default_order_key
        return (order_fields, order_key, direction)
    

    ## For Dynamic Ordering: Use the get_ordering() method of ListViews
    # It makes it possible to change the ordering based on values passed in over the querystring.
    ## @override
    def get_ordering(self):
        ## Default ordering will be '-updated'
        # ordering = self.request.GET.get('order', '-updated')
        order_fields, order_key, direction = self.get_order_settings()
        order_by = order_fields[order_key]
        ## If direction is 'desc' or invalid, use descending order:
        if (direction != 'asc'):
            order_by = '-' + order_by
        return order_by
    

    ## @override
    def get_queryset(self):
        ordering_by = self.get_ordering()
        query_set = Joke.objects.all()
        if ("search_qry" in self.request.GET): # Filter by search query
            search_qry = self.request.GET.get("search_qry") 
            ## Q lib: Allows compound queries using conditions, like <AND> & or <OR> |, etc.
            query_set = query_set.filter(Q(question__icontains=search_qry) | Q(answer__icontains=search_qry))
        ## Check if the route name is "my_jokes" to filter just that user's created jokes.
        if (self.request.resolver_match.url_name == "my_jokes"):   
            query_set = query_set.filter(user=self.request.user)
        elif ("slug" in self.kwargs): ## Filter by category OR tag
            slug = self.kwargs["slug"]
            if ("/category" in self.request.path_info): ## Filter by category
                query_set = query_set.filter(category__slug=slug)
            if ("/tag" in self.request.path_info): ## Filter by tag
                query_set = query_set.filter(tags__slug=slug)
        elif ("username" in self.kwargs): # Filter by joke creator
            username = self.kwargs["username"]
            query_set = query_set.filter(user__username=username)
        ## Adding in prefetch for optimization and to reduce dupe hits to the db
        return query_set.prefetch_related('category', 'user').order_by(ordering_by)
        # return query_set.order_by(ordering_by)


    ## @override
    def get_context_data(self, **kwargs):
        # Access the default context object name `joke_list`
        context = super().get_context_data(**kwargs)
        ## Compute #rating-bar width dynamically b/c `widthratio` does not work
        for joke in context["joke_list"]:
            if(joke.rating):
                joke.rating_width = joke.rating * 10
        # Check if the user is authenticated:
        if (self.request.user.is_authenticated):
            # Add the first joke related to the current user
            context['joke'] = self.model.objects.filter(user=self.request.user).first()
        else:
            context['joke'] = None
        context['user'] = self.request.user
        ## Add Ordering into the Context:
        order_fields, order_key, direction = self.get_order_settings()
        context['order'] = order_key
        context['direction'] = direction
        ## Slice all but the last order key, which is 'default'
        context['order_fields'] = list(order_fields.keys())[:-1]
        return context
## END class JokeListView


## BEGIN
class JokeUpdateView(SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    model = Joke
    # fields = ["question", "answer"]
    form_class = JokeForm
    success_message = "Joke updated successfully."


    ## @override
    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj.user
## END class
## END class based Views
## ------------------------------------------------------------------------------


## Functional Views aka View fcns
## ------------------------------------------------------------------------------
## We are using a fcnl View here so we can use JS and AJAX
# to send data back and forth from the client side to the server-side
# w/o a web page refresh
## If you are handling non-authenticated users client-side, you no longer have to give them access to the vote method
#  at all. You can add the @login_required decorator to the vote function (or any view function) to make the view 
# only accessible to logged-in users:
@login_required
def vote(request, slug):
    """ Vote like or dislike on a Joke AJAX

templates/jokes/joke_confirm_delete.html
{% extends "_base.html" %}

{% block title %}
  Delete Joke
{% endblock %}

{% block main %}
<div class="card border-primary m-auto mb-3 text-center" style="max-width: 30rem">
    <form id="delete-joke-form" method="post">
      {% csrf_token %}
      <p><strong>Are you sure you want to delete this joke?</strong></p>
      <p id="joke-{{joke.id}}">{{ joke.question }}</p>
      <button id="delete-joke-btn" class="btn btn-success form-control" type="submit">
        Confirm
      </button>
    </form>
  </div>
{% endblock %}

templates/jokes/joke_detail.html
{% extends "_base.html" %}
{% load static %}

{% block javascript %}
<!-- Sets constants used in jokes.js. These vars are set in the template so you can get
  a dynamic URL based on the slug of the Joke instance. -->
  <script>
    const ajaxURL = "{% url 'jokes:ajax-vote' joke.slug %}";
    // const isAuthenticated = {{ user.is_authenticated|lower }};
  </script>
<!-- Uses the `static` Django template tag to get the path to js/jokes.js, 
 but it only works if static dir has been loaded like a lib or pkg.  
 See Django template load tag above. -->
  <script src="{% static 'js/jokes.js' %}"></script>
{% endblock %}

{% block title %}
  Joke
{% endblock %}

{% block main %}
<div class="card border-primary m-auto mb-3 text-center" style="max-width: 30rem">
  <!-- The template has access to an auto-created variable called "joke" (the lowercase model name),
    containing the joke object. -->
  <div id="joke-{{joke.id}}-question" class="card-header">
    {{ joke.question }}
  </div>

  <div id="joke-{{joke.id}}-punchline" class="card-body text-primary">
    <h5 class="card-title">{{ joke.answer }}</h5>
  </div>

  <div id="joke-{{joke.id}}-footer" class="card-footer">
    <div id="joke-{{joke.id}}-cats-tags" class="border-bottom border-faded pb-2">
      <span id="joke-{{joke.id}}-category">
        <strong>Category:</strong> {{ joke.category.category }}<br>
      </span>
      {% for tag in joke.tags.all %}
        <span id="joke-{{joke.id}}-tag-{{tag.id}}" 
          class="badge rounded-pill bg-secondary">{{ tag.tag }}</span>
      {% endfor %}
    </div>

    
      <div class="border-bottom border-faded m-2 pb-2">
        {% if joke.user == user %}
          <a id="update-joke-{{joke.id}}-btn" href="{% url 'jokes:update' joke.slug %}" 
            class="btn btn-info btn-sm me-2">Update</a>
          <a id="delete-joke-{{joke.id}}-btn" href="{% url 'jokes:delete' joke.slug %}" 
            class="btn btn-danger btn-sm me-2">Delete</a>
          {% with votes=joke.votes %}
            <p>
              Your joke has <span id="num-votes">{{ votes.num_votes|default:'no' }} vote{{ votes.num_votes|pluralize }}.</span>
              {% if votes.num_votes %}
                It has <span id="likes">{{ votes.likes }} like{{ votes.likes|pluralize }}</span> and
                <span id="dislikes">{{ votes.dislikes }} dislike{{ votes.dislikes|pluralize }}.</span>
              {% endif %}
            </p>
          {% endwith %}
        {% elif user.is_authenticated %}
          {% csrf_token %}
          {% with votes=joke.votes %}
            <button id="dislike-button" class="btn btn-light" type="button">
              <i class="fas fa-thumbs-down text-danger"></i>
              <span id="dislikes">{{ votes.dislikes }}</span>
            </button>
            <button id="like-button" class="btn btn-light" type="button">
              <i class="fas fa-thumbs-up text-success"></i>
              <span id="likes">{{ votes.likes }}</span>
            </button>
            <!-- Output response after voting div -->
            <div id="output" class="text-info"></div>
            <span id="num-votes">{{ votes.num_votes }} vote{{ votes.num_votes|pluralize }}</span>
          {% endwith %}
        {% endif %}
      </div>
    
      <small class="text-muted">
        {% if joke.user.avatar %}
          <img id="author-avatar-pic" src="{{ joke.user.avatar.url }}" class="mt-1 rounded float-end" 
            alt="Author's avatar or profile picture"/>
        {% endif %}


        <span id="joke-{{joke.id}}-created"><span class="createdby-label">Created on: </span>
          {{ joke.created }}</span>
        <br />
        <span id="joke-{{joke.id}}-createdby"><span class="createdby-label">By: </span>
          {{ joke.user.username }}</span>
        <br />
        <span id="joke-{{joke.id}}-updated"><span class="createdby-label">Last updated:</span> 
          {{ joke.updated }}</span>
      </small>
    
  </div>
</div>
{% endblock %}

templates/jokes/joke_form.html
{% extends "_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Add/Update Joke
{% endblock %}

{% block main %}
<div class="card border-primary m-auto mb-3 p-3" style="max-width: 30rem">
  <!-- The template must include a form element, and the method must be “post”. -->
  <form method="post">
    <!-- Within the form element, you must include these 3 items: -->
    {% csrf_token %} <!-- 1. csrf_token template tag – This is a security measure that protects against
     cross site request forgery. -->
    
    {{ form|crispy }}

     <!-- <table id="joke-form-tbl" class="table">
      {{ form.as_table }} 
     2. A form interpolated variable to output the form fields and their labels.
     </table> -->
    <button id="submit-joke-btn" class="btn btn-success float-end" type="submit">
      Submit
    </button><!-- 3. A submit button -->
  </form>
</div>
{% endblock %}

templates/jokes/joke_list.html
{% extends "_base.html" %}

{% block title %}
Jokes
{% endblock %}

{% block main %}
<div class="row">
  <div class="col-12 col-md-2 col-lg-3">
    <h2>Jokes</h2>
  </div>

  <!-- Ordering/Sorting form or table -->
  <div class="col-12 col-md-8 col-lg-6">
    <form id="sort-form" class="my-2 mx-auto" style="max-width: 30rem;">
      <input type="hidden" name="search_qry" value="{{ request.GET.search_qry }}" style="display: none;"/> 

      <label id="order-by-lbl" class="my-1 me-2" for="order-select">
        Order By:
      </label>
      
      <select id="order-select" class="form-control me-sm-2" name="order">
        {% for field in order_fields %}
          <option id="{{ field }}-sort-option" 
            value="{{ field }}" 
            {% if order == field %}selected{% endif %}>{{ field|title }}</option>
        {% endfor %}
      </select>
      
      <div class="form-check form-check-inline">
        <input id="asc-radio-btn" 
          class="form-check-input" 
          type="radio" 
          name="direction" 
          value="asc" 
          {% if direction == 'asc' %}checked{% endif %} />
        <label id="asc-radio-lbl" class="form-check-label" for="asc-radio-btn">
          ASC
        </label>
      </div>

      <div class="form-check form-check-inline">
        <input id="desc-radio-btn" 
          class="form-check-input" 
          type="radio" 
          name="direction"
          value="desc" 
          {% if direction == 'desc' %}checked{% endif %} />
        <label id="desc-radio-lbl" class="form-check-label" for="desc-radio-btn">
          DESC
        </label>
      </div>
      
      <button id="sort-jokes-btn" 
        class="btn btn-primary btn-sm m-2" 
        type="submit" 
        value="Sort" 
        alt="Sort the joke list button">Sort</button>
    </form>
  </div>

  <!-- add-joke-btn -->
  <div class="col-12 col-md-2 col-lg-3 text-end">
    <a id="add-joke-btn" class="btn btn-success btn-sm m-2" href="{% url 'jokes:create' %}">
      + New Joke
    </a>
  </div>
</div>

<div class="table-responsive">
  <table id="jokes-list-tbl-page-{{ page_obj.number }}" class="table table-striped" style="min-width: 500px">
    <thead>
      {% with order=request.GET.order dir=request.GET.direction %}
        <tr>
          {% if order == 'joke' and dir == 'asc' %}
            <th>
              <a href="?order=joke&direction=desc&search_qry={{ request.GET.search_qry }}">Joke Set-Up</a>
            </th>
          {% else %}
            <th>
              <a href="?order=joke&direction=asc&search_qry={{ request.GET.search_qry }}">Joke Set-Up</a>
            </th>
          {% endif %}
          
          {% if order == 'category' and dir == 'asc' %}
            <th>
              <a href="?order=category&direction=desc&search_qry={{ request.GET.search_qry }}">Category/Tags</a>
            </th>
          {% else %}
            <th>
              <a href="?order=category&direction=asc&search_qry={{ request.GET.search_qry }}">Category/Tags</a>
            </th>
          {% endif %}

          {% if joke and joke.user == user %}
            <th>Actions</th>
          {% else %}
            {% if order == 'creator' and dir == 'asc' %}
              <th>
                <a href="?order=creator&direction=desc&search_qry={{ request.GET.search_qry }}">Created</a>
              </th>
            {% else %}
              <th>
                <a href="?order=creator&direction=asc&search_qry={{ request.GET.search_qry }}">Created</a>
              </th>
            {% endif %}
          {% endif %}
          <th>Rating (out of 10)</th>
        </tr>
      {% endwith %}
    </thead>

    <tbody>
      {% for joke in joke_list %}
      <tr>
        <td>
          <a id="joke-{{joke.id}}" href="{{ joke.get_absolute_url }}">{{ joke.question }}</a>
        </td>
        <td>
          <a id="category-joke-{{joke.id}}" 
            href="{% url 'jokes:category' joke.category.slug %}?order={{ order }}&direction={{ direction }}">
            {{ joke.category.category }}</a>
          <br />
          {% for tag in joke.tags.all %}
            <a id="tag-{{tag.id}}-joke-{{joke.id}}"
              href="{% url 'jokes:tag' tag.slug %}?order={{ order }}&direction={{ direction }}" 
              class="badge rounded-pill bg-secondary">{{ tag.tag }}</a>
          {% endfor %}
        </td>
        {% if joke.user == user %}
          <td id="edit-cell-joke-{{joke.id}}">
            <a id="update-btn-joke-{{joke.id}}" href="{% url 'jokes:update' joke.slug %}" 
              name="Update" alt="Update joke">
              <i class="fas fa-pencil-alt"></i>
            </a>
            &nbsp;
            <a id="delete-btn-joke-{{joke.id}}" href="{% url 'jokes:delete' joke.slug %}" 
              name="Delete" alt="Delete joke">
              <i class="far fa-trash-alt"></i>
            </a>
          </td>
        {% else %}
          <td id="created-cell-joke-{{joke.id}}">
            <span class="createdby-label">By:</span> 
            <a id="createdby-joke-{{joke.id}}"
              href="{% url 'jokes:creator' joke.user.username %}?order={{ order }}&direction={{ direction }}">
              {{ joke.user.username }}</a>
            <br />
            <span id="created-joke-{{joke.id}}"><span class="createdby-label">On:</span> 
            {{ joke.created|date:'SHORT_DATE_FORMAT' }}</span>
            <br />
            <span id="updated-joke-{{joke.id}}"><span class="createdby-label">Updated:</span><br/> 
            {{ joke.updated|date:'SHORT_DATE_FORMAT' }}</span>
          </td>
        {% endif %}

        {% with votes=joke.votes %}
          {% if votes.num_votes == 0 %}
            <td>
              <p id="rating-container-joke-{{joke.id}}" class="no-votes-yet">
                No rating yet!<br />
                Click the joke's set-up<br /> 
                to be the first to vote. :)
              </p>
            </td>
          {% else %}
            <td>
              <div id="rating-container-joke-{{joke.id}}" class="rating-container">
                <div id="rating-div-joke-{{joke.id}}" class="rating-div" 
                  title="Joke rating out of 10 = {{ votes.rating }}"> 
                  <!-- `widthratio` NO WORKY!!! NEVER WORKS! -->
                  <!-- <div id="rating" style="width:{% widthratio joke.rating 10 100 %}%;"></div> -->
                  <div id="rating-bar-joke-{{joke.id}}" 
                    class="rating-bar" 
                    style="--rating-width: {{ joke.rating_width }}%;"></div>
                </div>
                <div id="rating-joke-{{joke.id}}" class="rating">
                  {{ votes.rating }} 
                </div>
              </div>
              <div id="num-votes-joke-{{joke.id}}" class="num-votes">
                ({{ votes.likes }}<i class="fas fa-thumbs-up text-success mx-1"></i> and
                {{ votes.dislikes }}<i class="fas fa-thumbs-down text-danger mx-1"></i>)
              </div>
            </td>
          {% endif %}
        {% endwith %}
      </tr>

      {% empty %}
        <tr>
          <td colspan="3">No jokes found!</td>
        </tr>
      {% endfor %}
    </tbody>

  </table>
</div>

{% include 'includes/pagination.html' %}

{% endblock %}